/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AvisoLegalRouteImport } from "./routes/aviso-legal"
import { Route as ContactoRouteImport } from "./routes/contacto"
import { Route as DirectoRouteImport } from "./routes/directo"
import { Route as EntradasRouteImport } from "./routes/entradas"
import { Route as EventoRouteImport } from "./routes/evento"
import { Route as ExperienciaRouteImport } from "./routes/experiencia"
import { Route as InscripcionesRouteImport } from "./routes/inscripciones"
import { Route as PoliticaCookiesRouteImport } from "./routes/politica-cookies"
import { Route as PostulacionesRouteImport } from "./routes/postulaciones"
import { Route as PrivacidadRouteImport } from "./routes/privacidad"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: "/aviso-legal",
  path: "/aviso-legal",
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: "/contacto",
  path: "/contacto",
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoRoute = DirectoRouteImport.update({
  id: "/directo",
  path: "/directo",
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasRoute = EntradasRouteImport.update({
  id: "/entradas",
  path: "/entradas",
  getParentRoute: () => rootRouteImport,
} as any)
const EventoRoute = EventoRouteImport.update({
  id: "/evento",
  path: "/evento",
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: "/experiencia",
  path: "/experiencia",
  getParentRoute: () => rootRouteImport,
} as any)
const InscripcionesRoute = InscripcionesRouteImport.update({
  id: "/inscripciones",
  path: "/inscripciones",
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: "/politica-cookies",
  path: "/politica-cookies",
  getParentRoute: () => rootRouteImport,
} as any)
const PostulacionesRoute = PostulacionesRouteImport.update({
  id: "/postulaciones",
  path: "/postulaciones",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: "/privacidad",
  path: "/privacidad",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/aviso-legal": typeof AvisoLegalRoute
  "/contacto": typeof ContactoRoute
  "/directo": typeof DirectoRoute
  "/entradas": typeof EntradasRoute
  "/evento": typeof EventoRoute
  "/experiencia": typeof ExperienciaRoute
  "/inscripciones": typeof InscripcionesRoute
  "/politica-cookies": typeof PoliticaCookiesRoute
  "/postulaciones": typeof PostulacionesRoute
  "/privacidad": typeof PrivacidadRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/aviso-legal": typeof AvisoLegalRoute
  "/contacto": typeof ContactoRoute
  "/directo": typeof DirectoRoute
  "/entradas": typeof EntradasRoute
  "/evento": typeof EventoRoute
  "/experiencia": typeof ExperienciaRoute
  "/inscripciones": typeof InscripcionesRoute
  "/politica-cookies": typeof PoliticaCookiesRoute
  "/postulaciones": typeof PostulacionesRoute
  "/privacidad": typeof PrivacidadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/aviso-legal": typeof AvisoLegalRoute
  "/contacto": typeof ContactoRoute
  "/directo": typeof DirectoRoute
  "/entradas": typeof EntradasRoute
  "/evento": typeof EventoRoute
  "/experiencia": typeof ExperienciaRoute
  "/inscripciones": typeof InscripcionesRoute
  "/politica-cookies": typeof PoliticaCookiesRoute
  "/postulaciones": typeof PostulacionesRoute
  "/privacidad": typeof PrivacidadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/aviso-legal"
    | "/contacto"
    | "/directo"
    | "/entradas"
    | "/evento"
    | "/experiencia"
    | "/inscripciones"
    | "/politica-cookies"
    | "/postulaciones"
    | "/privacidad"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/aviso-legal"
    | "/contacto"
    | "/directo"
    | "/entradas"
    | "/evento"
    | "/experiencia"
    | "/inscripciones"
    | "/politica-cookies"
    | "/postulaciones"
    | "/privacidad"
  id:
    | "__root__"
    | "/"
    | "/aviso-legal"
    | "/contacto"
    | "/directo"
    | "/entradas"
    | "/evento"
    | "/experiencia"
    | "/inscripciones"
    | "/politica-cookies"
    | "/postulaciones"
    | "/privacidad"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ContactoRoute: typeof ContactoRoute
  DirectoRoute: typeof DirectoRoute
  EntradasRoute: typeof EntradasRoute
  EventoRoute: typeof EventoRoute
  ExperienciaRoute: typeof ExperienciaRoute
  InscripcionesRoute: typeof InscripcionesRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PostulacionesRoute: typeof PostulacionesRoute
  PrivacidadRoute: typeof PrivacidadRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/aviso-legal": {
      id: "/aviso-legal"
      path: "/aviso-legal"
      fullPath: "/aviso-legal"
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/contacto": {
      id: "/contacto"
      path: "/contacto"
      fullPath: "/contacto"
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/directo": {
      id: "/directo"
      path: "/directo"
      fullPath: "/directo"
      preLoaderRoute: typeof DirectoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/entradas": {
      id: "/entradas"
      path: "/entradas"
      fullPath: "/entradas"
      preLoaderRoute: typeof EntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/evento": {
      id: "/evento"
      path: "/evento"
      fullPath: "/evento"
      preLoaderRoute: typeof EventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/experiencia": {
      id: "/experiencia"
      path: "/experiencia"
      fullPath: "/experiencia"
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/inscripciones": {
      id: "/inscripciones"
      path: "/inscripciones"
      fullPath: "/inscripciones"
      preLoaderRoute: typeof InscripcionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/politica-cookies": {
      id: "/politica-cookies"
      path: "/politica-cookies"
      fullPath: "/politica-cookies"
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/postulaciones": {
      id: "/postulaciones"
      path: "/postulaciones"
      fullPath: "/postulaciones"
      preLoaderRoute: typeof PostulacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/privacidad": {
      id: "/privacidad"
      path: "/privacidad"
      fullPath: "/privacidad"
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ContactoRoute: ContactoRoute,
  DirectoRoute: DirectoRoute,
  EntradasRoute: EntradasRoute,
  EventoRoute: EventoRoute,
  ExperienciaRoute: ExperienciaRoute,
  InscripcionesRoute: InscripcionesRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PostulacionesRoute: PostulacionesRoute,
  PrivacidadRoute: PrivacidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
