/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ContactoRouteImport } from "./routes/contacto"
import { Route as DirectoRouteImport } from "./routes/directo"
import { Route as EntradasRouteImport } from "./routes/entradas"
import { Route as EventoRouteImport } from "./routes/evento"
import { Route as ExperienciaRouteImport } from "./routes/experiencia"
import { Route as PostulacionesRouteImport } from "./routes/postulaciones"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: "/contacto",
  path: "/contacto",
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoRoute = DirectoRouteImport.update({
  id: "/directo",
  path: "/directo",
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasRoute = EntradasRouteImport.update({
  id: "/entradas",
  path: "/entradas",
  getParentRoute: () => rootRouteImport,
} as any)
const EventoRoute = EventoRouteImport.update({
  id: "/evento",
  path: "/evento",
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: "/experiencia",
  path: "/experiencia",
  getParentRoute: () => rootRouteImport,
} as any)
const PostulacionesRoute = PostulacionesRouteImport.update({
  id: "/postulaciones",
  path: "/postulaciones",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/contacto": typeof ContactoRoute
  "/directo": typeof DirectoRoute
  "/entradas": typeof EntradasRoute
  "/evento": typeof EventoRoute
  "/experiencia": typeof ExperienciaRoute
  "/postulaciones": typeof PostulacionesRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/contacto": typeof ContactoRoute
  "/directo": typeof DirectoRoute
  "/entradas": typeof EntradasRoute
  "/evento": typeof EventoRoute
  "/experiencia": typeof ExperienciaRoute
  "/postulaciones": typeof PostulacionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/contacto": typeof ContactoRoute
  "/directo": typeof DirectoRoute
  "/entradas": typeof EntradasRoute
  "/evento": typeof EventoRoute
  "/experiencia": typeof ExperienciaRoute
  "/postulaciones": typeof PostulacionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/contacto"
    | "/directo"
    | "/entradas"
    | "/evento"
    | "/experiencia"
    | "/postulaciones"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/contacto"
    | "/directo"
    | "/entradas"
    | "/evento"
    | "/experiencia"
    | "/postulaciones"
  id:
    | "__root__"
    | "/"
    | "/contacto"
    | "/directo"
    | "/entradas"
    | "/evento"
    | "/experiencia"
    | "/postulaciones"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  DirectoRoute: typeof DirectoRoute
  EntradasRoute: typeof EntradasRoute
  EventoRoute: typeof EventoRoute
  ExperienciaRoute: typeof ExperienciaRoute
  PostulacionesRoute: typeof PostulacionesRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/contacto": {
      id: "/contacto"
      path: "/contacto"
      fullPath: "/contacto"
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/directo": {
      id: "/directo"
      path: "/directo"
      fullPath: "/directo"
      preLoaderRoute: typeof DirectoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/entradas": {
      id: "/entradas"
      path: "/entradas"
      fullPath: "/entradas"
      preLoaderRoute: typeof EntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/evento": {
      id: "/evento"
      path: "/evento"
      fullPath: "/evento"
      preLoaderRoute: typeof EventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/experiencia": {
      id: "/experiencia"
      path: "/experiencia"
      fullPath: "/experiencia"
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/postulaciones": {
      id: "/postulaciones"
      path: "/postulaciones"
      fullPath: "/postulaciones"
      preLoaderRoute: typeof PostulacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  DirectoRoute: DirectoRoute,
  EntradasRoute: EntradasRoute,
  EventoRoute: EventoRoute,
  ExperienciaRoute: ExperienciaRoute,
  PostulacionesRoute: PostulacionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
